# Generated by Django 4.0.3 on 2022-03-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=20)),
                ('num_dni', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('nombre', models.CharField(max_length=15)),
                ('autor', models.CharField(max_length=10)),
                ('genero', models.CharField(max_length=10)),
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=20)),
                ('num_dni', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
